image : mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

stages:
  - build
  - test

build:
  stage: build
  tags:
   - Docker
   - FB2
   - Windows
   - Runner
  script:
   - dotnet build ".C:\Users\kenne\source\repos\KompetenzDB\Programm\KompetenzDatenbank.sln"
    
test:
  stage: test
  tags:
   - Docker
   - FB2
   - Windows
   - Runner
  script:
    - dotnet test
